### ISSUE TITLE
Error with base-project & manage your database structure/migrations here set to NO

### ISSUE THREAD

**Issue by thejones** [subzerocloud/subzero-cli#29]
If I chose `No` for the manage DB structure I receive an error. I posted the command line output below. I did not look into it at this time I just thought I would post for visibility. 

```
➜  subzero_postgrest subzero base-project
? Enter the directory path where you want to create the project .
? Choose the starter kit postgrest-starter-kit (REST)
? Do you want to manage your database structure/migrations here? No
Downloading the base project..
sed: 1: "docker-compose.yml": extra characters at the end of d command
(node:10060) UnhandledPromiseRejectionWarning: Error: Command failed:
      docker run -u 501:20 -v /Users/knik/dev/scratch/subzero_postgrest/:/src subzerocloud/subzero-cli-tools
      sh -c 'rm -rf /Users/knik/dev/scratch/subzero_postgrest/./db && rm -rf /Users/knik/dev/scratch/subzero_postgrest/./tests/db/{rls,structure}.sql && rm -rf /Users/knik/dev/scratch/subzero_postgrest/./tests/rest/{auth,common,read}.js && sed -i "/### DB START/,/### DB END/d" docker-compose.yml && sed -i "/3000/,/db/{/3000/!d}" docker-compose.yml && sed -i "/db/d" docker-compose.yml'
sed: 1: "docker-compose.yml": extra characters at the end of d command

    at checkExecSyncError (child_process.js:574:11)
    at Object.execSync (child_process.js:611:13)
    at baseProject (/usr/local/lib/node_modules/subzero-cli/dist/main.js:93:29)
    at /usr/local/lib/node_modules/subzero-cli/dist/main.js:80:12
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:10060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ruslantalpa** [comment]
this might be related to the problem reported here which i fixed
https://github.com/subzerocloud/subzero-cli/issues/32

if it's not that, please reopen and i'll look into it
thank you for the feedback
