### ISSUE TITLE
Error when resetting db

### ISSUE THREAD

**Issue by scheiblr** [subzerocloud/subzero-cli#31]
I just got this error, when I try to reset the db:

```
TypeError: Cannot read property 'replace' of undefinedro dashboard
    at /home/schmittr/.node_modules_global/lib/node_modules/subzero-cli/dist/common.js:35:45
    at Array.reduce (<anonymous>)
    at runCmd (/home/schmittr/.node_modules_global/lib/node_modules/subzero-cli/dist/common.js:33:63)
    at runSql (/home/schmittr/.node_modules_global/lib/node_modules/subzero-cli/dist/watch.js:73:29)
    at resetDb (/home/schmittr/.node_modules_global/lib/node_modules/subzero-cli/dist/watch.js:41:14)
    at Dashboard._this.handleKeyPress (/home/schmittr/.node_modules_global/lib/node_modules/subzero-cli/dist/dashboard.js:197:30)
    at Element.<anonymous> (/home/schmittr/.node_modules_global/lib/node_modules/subzero-cli/dist/dashboard.js:247:23)
    at Element.EventEmitter._emit (/home/schmittr/.node_modules_global/lib/node_modules/subzero-cli/node_modules/blessed/lib/events.js:94:20)
    at Log.EventEmitter.emit (/home/schmittr/.node_modules_global/lib/node_modules/subzero-cli/node_modules/blessed/lib/events.js:131:12)
    at Program.<anonymous> (/home/schmittr/.node_modules_global/lib/node_modules/subzero-cli/node_modules/blessed/lib/widgets/screen.js:602:15)
```

**Comment by scheiblr** [comment]
This happened, because I renamed the varialbe `SUPER_USER` in the `.env` file. Changed it back and it works! Thanks @ruslantalpa for helping to find the error!
